[workspace]
members = [
    "lattice-core",
    "kyber-ml-kem",
    "dilithium-ml-dsa",
    "examples"
]
resolver = "2"

[workspace.dependencies]
rand = "0.8"
rand_chacha = "0.3"
sha3 = "0.10"
hex = "0.4" 