[package]
name = "lattice-core"
version = "0.1.0"
edition = "2021"
description = "Core lattice cryptography primitives for learning purposes"

[dependencies]
rand = { workspace = true }
rand_chacha = { workspace = true }
sha3 = { workspace = true }
hex = { workspace = true } 